os: linux
dist: xenial
language: python

jobs:
  include:
  - name: Python3.7
    python: "3.7"
    env:
    - TESTS_DIR=tests3

services:
  - docker

addons:
  apt:
    packages:
      - unixodbc-dev

before_script: |
    env | sort
    odbcinst -j
    # update unixODBC
    _PWD="$PWD"
    cd /tmp
    curl -sS -O 'ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.7.tar.gz'
    tar -xz -f unixODBC-2.3.7.tar.gz
    cd unixODBC-2.3.7
    ./configure 1> zzz_log_configure_std 2> zzz_log_configure_err
    make 1> zzz_log_make_std 2> zzz_log_make_err
    sudo make install 1> zzz_log_makeinstall_std 2> zzz_log_makeinstall_err
    ls -l
    cd "$_PWD"
    odbcinst -j
    #$TRAVIS_BUILD_DIR/travis/setup_test_dbs.sh
    # set up MSSQL in docker container
    docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=StrongPassword1' -p 1433:1433 --name mssql1 -d mcr.microsoft.com/mssql/server:2017-latest
    # install MSSQL drivers
    sudo bash -c 'curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -'
    sudo bash -c 'curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list'
    sudo apt-get update
    sudo ACCEPT_EULA=Y apt-get install msodbcsql17
    #dpkg -L msodbcsql17
    odbcinst -j
    # sometimes the first call to MSSQL in a docker container does not work, in which case
    # pause for a few seconds, see: https://github.com/microsoft/mssql-docker/issues/203
    docker exec -it mssql1 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'StrongPassword1' -Q 'SELECT @@VERSION' || sleep 10
    docker exec -it mssql1 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'StrongPassword1' -Q 'CREATE DATABASE test'

script:
  - python -VV
  - pwd
  - python ".\$TESTS_DIR\sqlservertests.py" "DRIVER={ODBC Driver 17 for SQL Server};SERVER=localhost;UID=sa;PWD=StrongPassword1;DATABASE=test"







# language: python
# sudo: false
# python:
#   - "2.7"
#   - "3.4"
#   - "3.5"
#   - "3.6"

# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
#     packages:
#     - gcc-4.8
#     - g++-4.8
#     - unixodbc-dev

# install:
#   - python setup.py install

# script: true
