os: linux
dist: bionic
language: python

jobs:
  include:
    - name: Python2.7
      python: "2.7"
      env:
        - TESTS_DIR=tests2
    #- name: Python3.5
    #  python: "3.5"
    #  env:
    #    - TESTS_DIR=tests3
    - name: Python3.6
      python: "3.6"
      env:
        - TESTS_DIR=tests3
    - name: Python3.7
      python: "3.7"
      env:
        - TESTS_DIR=tests3
    - name: Python3.8
      python: "3.8"
      env:
        - TESTS_DIR=tests3

services:
  - docker
  - mysql
  - postgresql

addons:
  postgresql: "11"
  apt:
    packages:
      - unixodbc
      - unixodbc-dev
      - odbc-postgresql

cache:
  directories:
    - travis_cache

install:
  - echo '[ODBC]' > /tmp/odbcinst.ini.new
  - echo 'Trace = yes' >> /tmp/odbcinst.ini.new
  - echo 'TraceFile = /tmp/pyodbcodbctrace.txt' >> /tmp/odbcinst.ini.new
  - echo '' >> /tmp/odbcinst.ini.new
  - cat /etc/odbcinst.ini >> /tmp/odbcinst.ini.new
  - sudo mv /etc/odbcinst.ini /etc/odbcinst.ini.orig
  - sudo mv /tmp/odbcinst.ini.new /etc/odbcinst.ini
  - cat /etc/odbcinst.ini
  # show cache
  - mkdir "$TRAVIS_BUILD_DIR/travis_cache" || true
  - ls -l "$TRAVIS_BUILD_DIR/travis_cache"
  - which odbcinst || true
  - sudo ls -l /usr || true
  #- sudo ls -ld /usr/bin/*odbc* || true
  #- sudo ls -ld /usr/local/bin/*odbc* || true
  #- sudo ls -ld /usr/lib/libodbc* || true
  #- sudo ls -ld /usr/lib64/libodbc* || true
  #- sudo ls -l /usr/lib/x86_64-linux-gnu/odbc || true
  #- odbcinst -j
  # install MySQL driver
  - cd /tmp
  - |
    if [ -f "$TRAVIS_BUILD_DIR/travis_cache/mysql-connector-odbc-5.3.13-linux-ubuntu16.04-x86-64bit.tar.gz" ]; then
      cp -v "$TRAVIS_BUILD_DIR/travis_cache/mysql-connector-odbc-5.3.13-linux-ubuntu16.04-x86-64bit.tar.gz" .
    else
      curl -v -O "https://www.mirrorservice.org/sites/ftp.mysql.com/Downloads/Connector-ODBC/5.3/mysql-connector-odbc-5.3.13-linux-ubuntu16.04-x86-64bit.tar.gz"
    fi
  - ls -l mysql-connector-odbc-5.3.13-linux-ubuntu16.04-x86-64bit.tar.gz
  - |
    if [ ! -f "$TRAVIS_BUILD_DIR/travis_cache/mysql-connector-odbc-5.3.13-linux-ubuntu16.04-x86-64bit.tar.gz" ]; then
      cp -v mysql-connector-odbc-5.3.13-linux-ubuntu16.04-x86-64bit.tar.gz "$TRAVIS_BUILD_DIR/travis_cache"
    fi
  - tar -xz -f mysql-connector-odbc-5.3.13-linux-ubuntu16.04-x86-64bit.tar.gz
  - sudo cp -v mysql-connector-odbc-5.3.13-linux-ubuntu16.04-x86-64bit/lib/libmyodbc5a.so /usr/lib/x86_64-linux-gnu/odbc/
  - sudo ls -l /usr/lib/x86_64-linux-gnu/odbc || true
  - echo '[MySQL ODBC 5.3 ANSI Driver]' > mysql_odbcinst.ini
  - echo 'Driver      = /usr/lib/x86_64-linux-gnu/odbc/libmyodbc5a.so' >> mysql_odbcinst.ini
  - echo 'UsageCount  = 1' >> mysql_odbcinst.ini
  - echo 'Threading   = 2' >> mysql_odbcinst.ini
  - sudo odbcinst -i -d -f mysql_odbcinst.ini
  # install the latest unixODBC driver manager (v2.3.1 is 10 years old and buggy)
  - cd /tmp
  - odbcinst --version
  - |
    if [ -f "$TRAVIS_BUILD_DIR/travis_cache/unixODBC-2.3.7.tar.gz" ]; then
      cp -v "$TRAVIS_BUILD_DIR/travis_cache/unixODBC-2.3.7.tar.gz" .
    else
      curl -v -O "http://www.unixodbc.org/unixODBC-2.3.7.tar.gz"
    fi
  - ls -l unixODBC-2.3.7.tar.gz
  - |
    if [ ! -f "$TRAVIS_BUILD_DIR/travis_cache/unixODBC-2.3.7.tar.gz" ]; then
      cp -v unixODBC-2.3.7.tar.gz "$TRAVIS_BUILD_DIR/travis_cache"
    fi
  - tar -xz -f unixODBC-2.3.7.tar.gz
  - cd unixODBC-2.3.7
  - sudo rm -v /usr/lib64/libodbc* || true
  - CPPFLAGS="-DSIZEOF_LONG_INT=8"
  - export CPPFLAGS
  #- ./configure --prefix=/usr --libdir=/usr/lib64 --sysconfdir=/etc --enable-gui=no --enable-drivers=no --enable-iconv --with-iconv-char-enc=UTF8 --with-iconv-ucode-enc=UTF16LE --enable-stats=no 1> zzz_log_configure_std 2> zzz_log_configure_err
  #- ./configure --prefix=/usr 1> zzz_log_configure_std 2> zzz_log_configure_err
  - ./configure --prefix=/usr --sysconfdir=/etc --enable-iconv --with-iconv-char-enc=UTF8 --with-iconv-ucode-enc=UTF16LE 1> zzz_log_configure_std 2> zzz_log_configure_err
  - tail -20 zzz_log_configure_std
  - tail -20 zzz_log_configure_err
  - make 1> zzz_log_make_std 2> zzz_log_make_err
  - tail -20 zzz_log_make_std
  - tail -20 zzz_log_make_err
  - sudo make install 1> zzz_log_install_std 2> zzz_log_install_err
  - tail -20 zzz_log_install_std
  - tail -20 zzz_log_install_err
  #- sudo ls -ld /usr/local/bin/*odbc* || true
  #- sudo /usr/local/bin/odbcinst -j || true
  - odbcinst --version
  # install MSSQL driver
  - sudo bash -c 'curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -'
  - sudo bash -c 'curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list'
  - sudo apt-get update
  - sudo ACCEPT_EULA=Y apt-get install msodbcsql17
  #- dpkg -L msodbcsql17
  # odbc info
  - odbcinst -j
  - cat /etc/odbcinst.ini
  - cat /etc/odbc.ini
  # show cache
  - ls -l "$TRAVIS_BUILD_DIR/travis_cache"
  # install pyodbc
  - cd "$TRAVIS_BUILD_DIR"
  - python -VV
  - python setup.py install

before_script:
  # set up SQL Server and test database in a docker container
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=StrongPassword1' -p 1433:1433 --name mssql1 -d mcr.microsoft.com/mssql/server:2017-latest
  - sleep 10  # give MSSQL in docker a chance to warm up, see: https://github.com/microsoft/mssql-docker/issues/203
  - docker exec -it mssql1 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'StrongPassword1' -Q "SELECT @@VERSION" || sleep 10
  - echo "*** create test database in SQL Server"
  - docker exec -it mssql1 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'StrongPassword1' -Q "CREATE DATABASE test"
  # create test database in PostgreSQL
  - psql -c "SELECT version()" -U postgres
  - psql -c "CREATE DATABASE test WITH encoding='UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8'" -U postgres
  - psql -l
  # create test database in MySQL"
  - mysql -e "STATUS"
  - mysql -e "CREATE DATABASE test"

script:
  - cd "$TRAVIS_BUILD_DIR"
  #### run SQL Server tests
  ###- python "./$TESTS_DIR/sqlservertests.py" -v "DRIVER={ODBC Driver 17 for SQL Server};SERVER=localhost;UID=sa;PWD=StrongPassword1;DATABASE=test"
  #### run PostgreSQL tests
  ###- python "./$TESTS_DIR/pgtests.py" -v "DRIVER={PostgreSQL Unicode};SERVER=localhost;UID=postgres;DATABASE=test"
  #### run MySQL tests
  ###- python "./$TESTS_DIR/mysqltests.py" -v "DRIVER={MySQL ODBC 5.3 ANSI Driver};SERVER=localhost;DATABASE=test;CHARSET=utf8mb4"
  - python "./$TESTS_DIR/keith.py"
  - tail -1000 /tmp/pyodbcodbctrace.txt
