
# https://packaging.python.org/appveyor/

# This can't build 3.3 or 3.4 versions without a special build.cmd script,
# defined in the article above. I don't feel like messing with it and am just
# using this for build testing right now, so I'm not going to test every
# version.

environment:

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python27"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python34"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python34"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python35"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python35"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python36"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python36"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python37"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python37"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python38"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python38"
      PYTHON_ARCH: "64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python36"
      PYTHON_ARCH: "64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: "C:\\Python36"
      PYTHON_ARCH: "64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python36"
      PYTHON_ARCH: "64"

build: off

test_script:
  - echo KME APPVEYOR_BUILD_WORKER_IMAGE: %APPVEYOR_BUILD_WORKER_IMAGE%
  - echo KME PYTHON: %PYTHON%
  - echo KME PYTHON_ARCH: %PYTHON_ARCH%
  - "%PYTHON%\\python.exe setup.py build"
