# version: '{branch} - #{build}'

image: Visual Studio 2015

platform:
  - x64

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\utils\\build-python.cmd"

  matrix:

    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2008  # does not exist
    #   PYTHON: "C:\\Python27"
    #   PYTHON_ARCH: "64"
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2010  # does not exist
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.13"
      PYTHON_ARCH: "64"

    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2010  # does not exist
    #   PYTHON: "C:\\Python34"
    #   PYTHON_ARCH: "64"
    # # this works:
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   PYTHON: "C:\\Python34"
    #   PYTHON_ARCH: "64"

    # # this works:
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.5"
      PYTHON_ARCH: "64"
    # # this works:
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #   PYTHON: "C:\\Python35"
    #   PYTHON_ARCH: "64"
    # # this fails: "LINK : fatal error LNK1158: cannot run 'rc.exe'"
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    #   PYTHON: "C:\\Python35"
    #   PYTHON_ARCH: "64"

    # these all work:
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   PYTHON: "C:\\Python36"
    #   PYTHON_ARCH: "64"
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #   PYTHON: "C:\\Python36"
    #   PYTHON_ARCH: "64"
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.8"
      PYTHON_ARCH: "64"

build_script:
  - "echo APPVEYOR_REPO_NAME         : %APPVEYOR_REPO_NAME%"
  - "echo APPVEYOR_REPO_BRANCH       : %APPVEYOR_REPO_BRANCH%"
  - "echo APPVEYOR_BUILD_FOLDER      : %APPVEYOR_BUILD_FOLDER%"
  - "echo APPVEYOR_BUILD_WORKER_IMAGE: %APPVEYOR_BUILD_WORKER_IMAGE%"
  - "echo PYTHON     : %PYTHON%"
  - "echo PYTHON_ARCH: %PYTHON_ARCH%"
  - dir
  - '%PYTHON%\\python.exe -c "import platform; print(platform.python_build(), platform.python_compiler())"'
  - "%WITH_COMPILER% %PYTHON%\\python.exe setup.py build"
  - "%PYTHON%\\python.exe setup.py install"
  - '%PYTHON%\\python.exe -c "import pyodbc; print(pyodbc.version)"'
  - dir build

test_script:
  - echo RUN TESTS HERE!

after_test:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip --no-warn-script-location"
  - "%PYTHON%\\python.exe -m pip install wheel --no-warn-script-location"
  - "%WITH_COMPILER% %PYTHON%\\python.exe setup.py bdist_wheel"
  - dir /s dist

artifacts:
  - path: 'dist\*.whl'
    name: wheels
