# version: '{branch} - #{build}'

image: Visual Studio 2015

# platform:
#   - x64

# cache:
#   - dist -> appveyor.yml

# services:
#   - mssql2008r2sp2

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # http://stackoverflow.com/a/13751649/163740
    # http://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros#microsoft-specific-predefined-macros
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\utils\\build-python.cmd"

  matrix:

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      PYTHON: "C:\\Python27"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      PYTHON: "C:\\Python27-x64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      PYTHON: "C:\\Python34"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      PYTHON: "C:\\Python34-x64"

    # Python 3.5 needs at least the VS2015 image
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python35"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python35-x64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python36"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python36-x64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python37"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python37-x64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python38"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python38-x64"
      TESTS_DIR: tests3
      MSSQL_NAME: SQL2008R2SP2
      MSSQL_CONN: Server=(local)\%MSSQL_NAME%;Database=test_db;UID=sa;PWD=Password12!

build_script:
  - "echo APPVEYOR_BUILD_FOLDER: %APPVEYOR_BUILD_FOLDER%"
  - "echo APPVEYOR_BUILD_WORKER_IMAGE: %APPVEYOR_BUILD_WORKER_IMAGE%"
  - "echo APPVEYOR_JOB_ID: %APPVEYOR_JOB_ID%"
  - "echo APPVEYOR_JOB_NAME: %APPVEYOR_JOB_NAME%"
  - "echo APPVEYOR_JOB_NUMBER: %APPVEYOR_JOB_NUMBER%"
  - "echo PYTHON: %PYTHON%"
  - "echo TESTS_DIR: %TESTS_DIR%"
  - "echo MSSQL_NAME: %MSSQL_NAME%"
  - "echo MSSQL_CONN: %MSSQL_CONN%"
  #- dir /B
  - "%PYTHON%\\python -c \"import platform; print(platform.python_build(), platform.python_compiler())\""
  - "%WITH_COMPILER% %PYTHON%\\python setup.py build"
  - "%PYTHON%\\python setup.py install"
  - "%PYTHON%\\python -c \"import pyodbc; print(pyodbc.version)\""
  #- dir /B build

test_script:
  - echo RUN TESTS HERE!
  # - echo MS SQL Server tests
  # - "sqlcmd -S \"(local)\%MSSQL_NAME%\" -U sa -P \"Password12!\" -Q \"SELECT @@VERSION\""
  # - "sqlcmd -S \"(local)\%MSSQL_NAME%\" -U sa -P \"Password12!\" -Q \"CREATE DATABASE test_db\""
  # - "%PYTHON%\\python %TESTS_DIR%\sqlservertests.py %MSSQL_CONN%"

after_test:
  - "%PYTHON%\\python -m pip install --upgrade pip --no-warn-script-location"
  - "%PYTHON%\\python -m pip install wheel --no-warn-script-location"
  - "%WITH_COMPILER% %PYTHON%\\python setup.py bdist_wheel"
  - dir /B dist
  - "7z a %APPVEYOR_BUILD_FOLDER%\\dist\\wheels.zip dist\\*.whl"

artifacts:
  - path: 'dist\*.whl'
  - path: 'dist\wheels.zip'
