
# https://packaging.python.org/appveyor/

# This can't build 3.3 or 3.4 versions without a special build.cmd script,
# defined in the article above. I don't feel like messing with it and am just
# using this for build testing right now, so I'm not going to test every
# version.

environment:

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python27"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python27-x64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python36"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python36-x64"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py build"
