# version: '{branch} - #{build}'

image: Visual Studio 2015

# platform:
#   - x64

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # http://stackoverflow.com/a/13751649/163740
    # http://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros#microsoft-specific-predefined-macros
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\utils\\build-python.cmd"

  matrix:

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      PYTHON: "C:\\Python27"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      PYTHON: "C:\\Python27-x64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      PYTHON: "C:\\Python34"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      PYTHON: "C:\\Python34-x64"

    # Python 3.5 needs at least the VS2015 image
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python35"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python35-x64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python36"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python36-x64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python37"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python37-x64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python38"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python38-x64"

build_script:
  - "echo APPVEYOR_BUILD_FOLDER: %APPVEYOR_BUILD_FOLDER%"
  - "echo APPVEYOR_BUILD_WORKER_IMAGE: %APPVEYOR_BUILD_WORKER_IMAGE%"
  - "echo PYTHON: %PYTHON%"
  #- dir /B
  - "%PYTHON%\\python.exe -c \"import platform; print(platform.python_build(), platform.python_compiler())\""
  - "%WITH_COMPILER% %PYTHON%\\python.exe setup.py build"
  - "%PYTHON%\\python.exe setup.py install"
  - "%PYTHON%\\python.exe -c \"import pyodbc; print(pyodbc.version)\""
  #- dir /B build

test_script:
  - echo RUN TESTS HERE!

after_test:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip --no-warn-script-location"
  - "%PYTHON%\\python.exe -m pip install wheel --no-warn-script-location"
  - "%WITH_COMPILER% %PYTHON%\\python.exe setup.py bdist_wheel"
  - dir /B dist

artifacts:
  - path: 'dist\*.whl'
